// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/payment/payment.proto

package payment

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Transaction struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId              string   `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Amount               int64    `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Transaction) Reset()         { *m = Transaction{} }
func (m *Transaction) String() string { return proto.CompactTextString(m) }
func (*Transaction) ProtoMessage()    {}
func (*Transaction) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{0}
}

func (m *Transaction) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Transaction.Unmarshal(m, b)
}
func (m *Transaction) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Transaction.Marshal(b, m, deterministic)
}
func (m *Transaction) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Transaction.Merge(m, src)
}
func (m *Transaction) XXX_Size() int {
	return xxx_messageInfo_Transaction.Size(m)
}
func (m *Transaction) XXX_DiscardUnknown() {
	xxx_messageInfo_Transaction.DiscardUnknown(m)
}

var xxx_messageInfo_Transaction proto.InternalMessageInfo

func (m *Transaction) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Transaction) GetOrderId() string {
	if m != nil {
		return m.OrderId
	}
	return ""
}

func (m *Transaction) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Transaction) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type Response struct {
	Success              bool         `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Transaction          *Transaction `protobuf:"bytes,2,opt,name=transaction,proto3" json:"transaction,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_78ce6d11f0608d17, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetTransaction() *Transaction {
	if m != nil {
		return m.Transaction
	}
	return nil
}

func init() {
	proto.RegisterType((*Transaction)(nil), "payment.Transaction")
	proto.RegisterType((*Response)(nil), "payment.Response")
}

func init() {
	proto.RegisterFile("proto/payment/payment.proto", fileDescriptor_78ce6d11f0608d17)
}

var fileDescriptor_78ce6d11f0608d17 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x03, 0x31,
	0x10, 0x85, 0xd9, 0xad, 0x74, 0xb7, 0xb3, 0x50, 0xe8, 0x20, 0x12, 0x15, 0xa1, 0xf4, 0xd4, 0x53,
	0x85, 0x0a, 0x9e, 0xbc, 0x88, 0x27, 0x2f, 0x22, 0xd1, 0xa3, 0x50, 0x62, 0x32, 0x87, 0x1c, 0x9a,
	0x2c, 0xc9, 0xac, 0xe0, 0xbf, 0x17, 0xc6, 0x8d, 0xee, 0xa1, 0xa7, 0xf0, 0x7d, 0x19, 0xf2, 0xde,
	0x04, 0xae, 0xfb, 0x14, 0x39, 0xde, 0xf6, 0xe6, 0xfb, 0x48, 0x81, 0xcb, 0xb9, 0x13, 0x8b, 0xcd,
	0x88, 0x9b, 0x08, 0xdd, 0x7b, 0x32, 0x21, 0x1b, 0xcb, 0x3e, 0x06, 0x5c, 0x42, 0xed, 0x9d, 0xaa,
	0xd6, 0xd5, 0x76, 0xa1, 0x6b, 0xef, 0xf0, 0x12, 0xda, 0x98, 0x1c, 0xa5, 0x83, 0x77, 0xaa, 0x16,
	0xdb, 0x08, 0x3f, 0x3b, 0xbc, 0x80, 0xb9, 0x39, 0xc6, 0x21, 0xb0, 0x9a, 0xad, 0xab, 0xed, 0x4c,
	0x8f, 0x84, 0x37, 0x00, 0x36, 0x91, 0x61, 0x72, 0x07, 0xc3, 0xea, 0x4c, 0xee, 0x16, 0xa3, 0x79,
	0xe4, 0xcd, 0x07, 0xb4, 0x9a, 0x72, 0x1f, 0x43, 0x26, 0x54, 0xd0, 0xe4, 0xc1, 0x5a, 0xca, 0x59,
	0x22, 0x5b, 0x5d, 0x10, 0xef, 0xa1, 0xe3, 0xff, 0x5a, 0x12, 0xdd, 0xed, 0xcf, 0x77, 0x65, 0x89,
	0x49, 0x65, 0x3d, 0x1d, 0xdc, 0xbf, 0xc0, 0xf2, 0xf5, 0x77, 0xe6, 0x8d, 0xd2, 0x97, 0xb7, 0x84,
	0x0f, 0xb0, 0x7a, 0x92, 0xf0, 0xe9, 0x9a, 0x27, 0x5f, 0xba, 0x5a, 0xfd, 0xd9, 0xd2, 0xf0, 0x73,
	0x2e, 0xdf, 0x75, 0xf7, 0x13, 0x00, 0x00, 0xff, 0xff, 0x02, 0xed, 0xe8, 0x63, 0x4d, 0x01, 0x00,
	0x00,
}
